### PR TITLE
Make build.jl aware of other blas vendors besides OpenBLAS

### PR DESCRIPTION
**Pull request by vchuravy**
This makes the issue in https://github.com/dmlc/mxnet/issues/3244 more apparent to users.

### CODE REVIEW

**Comment by vchuravy** [comment]
dcbcdd1 is independent, but quite important.

**Comment by vchuravy** [comment]
@pluskid The changes are quite innocent, but I would have waited for the CI ;) (which seems to be quite back-logged)

**Comment by pluskid** [comment]
@vchuravy I was in a hurry merging them without waiting for the CI because I wanted to have the changes to the build script patched into the current v0.1.0 release, which I already tagged. The CIs are annoyingly slow.

**Comment by tkelman** [comment]
replace the git tag too

**Comment by pluskid** [comment]
@tkelman Yes, I manually replaced the SHA in the PR to METADATA.jl to an updated version.

**Comment by tkelman** [comment]
the git tag at https://github.com/dmlc/MXNet.jl/releases is now inconsistent though

**Comment by pluskid** [comment]
@tkelman nice catch! hmm... yes, this is complicated. Let me delete the release tag and start over again...

**Pull request merged**
