### PR TITLE
Installation failed with julia 0.6.1

### PR DESCRIPTION
**Pull request by iblis17**
<pre>
julia> versioninfo()
Julia Version 0.6.1
Commit 0d7248e2ff (2017-10-24 22:15 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD FX-8320E Eight-Core Processor
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Piledriver)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, bdver1)
</pre>

<pre>
julia> Pkg.add("MXNet")
INFO: Installing Formatting v0.3.0
INFO: Installing JSON v0.15.2
INFO: Installing MXNet v0.2.3
INFO: Building MXNet
INFO: Found a CUDA installation.
INFO: Attempting to Create directory /home/fps/.julia/v0.6/MXNet/deps/src
INFO: Directory /home/fps/.julia/v0.6/MXNet/deps/src already created
INFO: Attempting to Create directory /home/fps/.julia/v0.6/MXNet/deps/usr/lib
INFO: Directory /home/fps/.julia/v0.6/MXNet/deps/usr/lib already created
INFO: Attempting to Create directory /home/fps/.julia/v0.6/MXNet/deps/src/mxnet
INFO: Directory /home/fps/.julia/v0.6/MXNet/deps/src/mxnet already created
INFO: Changing Directory to /home/fps/.julia/v0.6/MXNet/deps/src/mxnet
INFO: Changing Directory to /home/fps/.julia/v0.6/MXNet/deps/src/mxnet
INFO: Changing Directory to /home/fps/.julia/v0.6/MXNet/deps/src/mxnet
M	cub
HEAD is now at 8713d25... [R][DOC] update R installation guide (#6457)
INFO: Changing Directory to /home/fps/.julia/v0.6/MXNet/deps/src/mxnet
fatal: reference is not a tree: 89de7ab20167909bc2c4f8acd397671c47cf3c0d
Unable to checkout '89de7ab20167909bc2c4f8acd397671c47cf3c0d' in submodule path 'cub'
============================================================[ ERROR: MXNet ]============================================================

LoadError: failed process: Process(`git submodule update --init`, ProcessExited(1)) [1]
while loading /home/fps/.julia/v0.6/MXNet/deps/build.jl, in expression starting on line 58

========================================================================================================================================

============================================================[ BUILD ERRORS ]============================================================

WARNING: MXNet had build errors.

 - packages with build errors remain installed in /home/fps/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("MXNet")`
 - build a single package by running its `deps/build.jl` script

========================================================================================================================================
INFO: Package database updated
</pre>

### CODE REVIEW

**Comment by iblis17** [comment]
hmm... turning this issue into a PR makes the post owner changed ?!

**Comment by fps** [comment]
Anyways, I disabled the check for CUDA_HOME in <code>deps/build.jl</code> as seen in my second message in this issue-thread. The error I get seems to be unrelated:

<pre>
[...]
fatal: reference is not a tree: 89de7ab20167909bc2c4f8acd397671c47cf3c0d
[...]
Unable to checkout '89de7ab20167909bc2c4f8acd397671c47cf3c0d' in submodule path 'cub'
[...]
</pre>

Regarding the error from calling <code>deps/build.jl</code> manually: No, it's there:
<pre>
fps@mango 05:46:13 ~/.../v0.6/MXNet (master) $ pwd
/home/fps/.julia/v0.6/MXNet
fps@mango 05:46:47 ~/.../v0.6/MXNet (master) $ ls deps/cblas.h 
deps/cblas.h
</pre>

Possibly something about my installation is broken? I just got a tarball from julialang, extracted it, <code>ls -l</code>'ed it's <code>juila</code> binary and then tried to install MXNet..

**Comment by fps** [comment]
I think I possibly just called <code>build.jl</code> from the wrong <code>$PWD (./MXNet/)</code>. Building from <code>MXNet/deps</code> seems to progress some more..

**Comment by iblis17** [comment]
Problem solved (on irc).

For record, restart Julia session, then issue:
```julia
julia> ENV["MXNET_COMMIT"] = "0.12.0"

julia> Pkg.build("MXNet")
```

**Pull request merged**
