### PR TITLE
Fix mx.sum regression

### PR DESCRIPTION
**Pull request by MikeInnes**
Possible fix for #132. I think this should recover the original behaviour, although it may be better to simply add `::SymbolicNode` dispatch to the currently untyped symbolic methods.

### CODE REVIEW

**Comment by vchuravy** [comment]
Good catch. I will add a PR to fix the dispatch.

@pluskid Should we stop extending base methods and require the use of `mx.sum`? Especially with the planned proliferation of methods in MXNet proper that follow `numpy` semantics instead of Julia semantics.

**Comment by pluskid** [comment]
@MikeInnes Thanks!
@vchuravy Yes, I think it is good idea to require using `mx.` prefix before everything gets super confusing. We should emphasize this in the doc.

**Comment by vchuravy** [comment]
@pluskid The only problem with that is that we then lose the niceness of
```
A = mx.Variable(:A)
B = mx.Variable(:B)
C = A + B'
```

**Comment by vchuravy** [comment]
I think this was mostly done with #134?

**Pull request closed without merging**
