### PR TITLE
cleanup docs a bit more

### PR DESCRIPTION
**Pull request by vchuravy**
Another round of cleanups.

### CODE REVIEW

**Comment by vchuravy** [comment]
This should fix most of the docs except for https://github.com/JuliaDocs/Documenter.jl/issues/247, https://github.com/JuliaDocs/Documenter.jl/issues/228 and https://github.com/JuliaDocs/Documenter.jl/issues/227

@pluskid can we tag a new release for #126 or do you want to wait on #123?

**Comment by pluskid** [comment]
Do you know if Julia v0.5 is going to be released soon? If it is very close, we could try to wait for that and try to fix most of 0.5 related warnings before tagging a new version. If is it not going to happen soon, then I'm OK with tagging after #126.

**Comment by vchuravy** [comment]
The remaining v0.5 warnings are coming from https://github.com/JuliaLang/Formatting.jl/issues/23 and the fact that `Compat` can't handle `Dict([x=>x for x ... ])`. The dict issue we can't directly fix until we drop support for v0.4, but it is fairly subdued.

If I would venture a guess v0.5 should be released within the next two weeks, as long as the current RC has no show-stoppers.

**Comment by pluskid** [comment]
Thanks! Sounds good. I think we can make a quick new version.

**Pull request merged**
