### PR TITLE
[WIP/RFC] Initial support for modules

### PR DESCRIPTION
**Pull request by vchuravy**
This is one of the bigger features that the Python frontend has that we are currently missing.
My goals with this are to support several different use-cases:

- Bucketing: #129 
- Custom operators in Julia: #39, #77, #166, #167 
- For optimal performance I plan on integrating this with CUDAnative.jl for Julia v0.6 so that custom operators can be executed on the GPU

So far I have been working on a straight port of the Python functionality, but I would be interested in a bit more design discussion.

PRs against this branch are very welcome.

### CODE REVIEW

**Comment by Arkoniak** [comment]
Thank you, it would be nice to have modules api implemented. I have couple of preliminary questions
1. Now `Nullable{...}` should be used instead of `Union{Void, ...}`?
2. May be make organization of modules in the same way as optimizers? I mean, move AbstractModule to "src/module.jl" and all implementations in "src/modules/...". it looks more natural to general structure of MXNet.jl.
3. Should `SymbolModule` support `AbstractDataProvider`? There is slight inconvenience, that `AbstractDataProvider` has its own functions for data/label names, so user will be forced to enter same information twice, moreover dataprovider's and module data_names can conflict. May be it would be better to infer names from `DataProvider` but unfortunately it is only possible during `bind`.
4. Are there any reasons to put modules in their own namespace? At first glance new functions shouldn't conflict with previous code, and `mx.Module.SymbolModule` looks redundant. But may be I am missing something important.

**Comment by vchuravy** [comment]
1. Yes, `Nullable` is preferred. 
2. Will do that on the next push.
3. Will have to think about that.
4. Right now it is to make sure that things won't conflict and we can reexport the important bindings later once the interface has stabilised.

**Comment by vchuravy** [comment]
Rebased to include #179.

**Comment by vchuravy** [comment]
@pluskid If you have the time, it would be nice to get your opinion of the implementation so far.

**Comment by pluskid** [comment]
@vchuravy Thanks a lot! Currently I did not have time to go through it very carefully. But quickly scanning it and it looks good. 

Regarding SequentialModule in another PR, maybe for `output_shapes`, instead of using Dict, we still keep vector of name, shape pairs?

**Comment by vchuravy** [comment]
Some thoughts I had over the last days:

* `@pluskid` and I had a conversation in #153 on not doing automatic data parallelism in `SymbolModule` e.g. not using `ExecutorGroup`, what we could do instead is to simplify `SymbolModule` and provide a `DataParallelModule` wraps a module and parallelises it over a set of devices. This would split the complexity of `ExecutorGroup` and might make the API simpler.
* For sequential modules the wiring of input to output needs to be done during bind and there should be no need to pass data into backwards and forwards.

**Comment by pluskid** [comment]
@vchuravy I agree that the current implementation is a bit complicated due to auto data par. `DataParallelModule` might be a good idea. I would support it if it solve the issue. Though maybe we need to inspect and design a bit more carefully. For example, data par implementation needs to make sure the gradients are aggregated via the same `KVStore`.

**Comment by iblis17** [comment]
😱 why close this?

**Comment by vchuravy** [comment]
I don't have any time to devote to this and I don't want the illusion of progress,

**Pull request closed without merging**
