### PR TITLE
[WIP] nnvm support

### PR DESCRIPTION
**Pull request by pluskid**
All unit test passed except `bind` for `Float64` (ref dmlc/nnvm#52)
- [x] wait for dmlc/nnvm#52 to be resolved
- [x] modify all examples to reflect new API changes (mostly modify `data=xxx` in layer construction to use positional argument instead)
- [ ] clearly document somewhere the new calling convention of NDArray op vs Symbolic op in potential ambiguity situations

### CODE REVIEW

**Comment by pluskid** [comment]
I can confirm locally that all the test has passed now.

**Comment by vchuravy** [comment]
So this is depending on the `nvvm` branch being merged to mxnet proper?

**Comment by pluskid** [comment]
Yes, `nnvm` branch in mxnet needs to be merged before we merge this.

**Comment by Arkoniak** [comment]
So, is it possible to merge this branch now? Because nnvm branch in mxnet already merged. Right now master branch of MXNet.jl is broken, it can't even compile and travis-ci fails all tests for new pr. At least, I've tried to made a pr https://github.com/dmlc/MXNet.jl/pull/160 and it segfaulted.

May be some help is required? I would be glad to be of assistance.

**Comment by Arkoniak** [comment]
By the way, `to_graphviz` function in visualize is broken - mxnet `to_json` use "attr" keyword instead of "param" now.

**Comment by pluskid** [comment]
@Arkoniak Thanks! Can you try to pull locally the nnvm branch and test if it works with the latest mxnet? If the test passes, we could merge this branch right away. Most of the functionality should already be ready, maybe just with some small tweaks to accommodate later changes in nnvm.

**Comment by Arkoniak** [comment]
@pluskid I've build travis report from my own fork of MXNet: https://travis-ci.org/Arkoniak/MXNet.jl/builds/188769522. I hope it is visible publicaly. Unfortunately, all three julia versions are broken:
1. Julia 0.4 shows lots of ambiguity warnings 
```
WARNING: New definition 

    Activation(MXNet.mx.SymbolicNode...) at /home/travis/.julia/v0.4/MXNet/src/symbolic-node.jl:693

is ambiguous with: 

    Activation(MXNet.mx.NDArray...) at /home/travis/.julia/v0.4/MXNet/src/ndarray.jl:1031.

To fix, define 

    Activation()

before the new definition.
```
and breaks with 
```
INFO: SymbolicNode::dot

WARNING: [a] concatenation is deprecated; use collect(a) instead

 in depwarn at deprecated.jl:73

 in oldstyle_vcat_warning at ./abstractarray.jl:29

 in vect at abstractarray.jl:32

 in _set_value at /home/travis/.julia/v0.4/MXNet/src/ndarray.jl:995

 in _set_value at /home/travis/.julia/v0.4/MXNet/src/ndarray.jl:1031

 in setindex! at /home/travis/.julia/v0.4/MXNet/src/ndarray.jl:347

 in ones at /home/travis/.julia/v0.4/MXNet/src/ndarray.jl:238

 in ones at /home/travis/.julia/v0.4/MXNet/src/ndarray.jl:234

 in test_dot at /home/travis/.julia/v0.4/MXNet/test/unittest/symbolic-node.jl:119

 in include at ./boot.jl:261

 in include_from_node1 at ./loading.jl:333

 in anonymous at /home/travis/.julia/v0.4/MXNet/test/runtests.jl:10

 in map at abstractarray.jl:1305

 in test_dir at /home/travis/.julia/v0.4/MXNet/test/runtests.jl:9

 in include at ./boot.jl:261

 in include_from_node1 at ./loading.jl:333

 in process_options at ./client.jl:280

 in _start at ./client.jl:378

while loading /home/travis/.julia/v0.4/MXNet/test/unittest/symbolic-node.jl, in expression starting on line 139

ERROR: LoadError: LoadError: MethodError: `convert` has no method matching convert(::Type{Ptr{Ptr{Void}}}, ::Array{Union{},1})

This may have arisen from a call to the constructor Ptr{Ptr{Void}}(...),

since type constructors fall back to convert methods.

Closest candidates are:

  call{T}(::Type{T}, ::Any)

  convert{T}(::Type{Ptr{T}}, !Matched::UInt64)

  convert{T}(::Type{Ptr{T}}, !Matched::Int64)

  ...

 [inlined code] from deprecated.jl:417

 in unsafe_convert at no file:0

 [inlined code] from /home/travis/.julia/v0.4/MXNet/src/base.jl:55

 in _set_value at /home/travis/.julia/v0.4/MXNet/src/ndarray.jl:1006

 in _set_value at /home/travis/.julia/v0.4/MXNet/src/ndarray.jl:1031

 in setindex! at /home/travis/.julia/v0.4/MXNet/src/ndarray.jl:347

 in ones at /home/travis/.julia/v0.4/MXNet/src/ndarray.jl:238

 in ones at /home/travis/.julia/v0.4/MXNet/src/ndarray.jl:234

 in test_dot at /home/travis/.julia/v0.4/MXNet/test/unittest/symbolic-node.jl:119

 in include at ./boot.jl:261

 in include_from_node1 at ./loading.jl:333

 in anonymous at /home/travis/.julia/v0.4/MXNet/test/runtests.jl:10

 in map at abstractarray.jl:1305

 in test_dir at /home/travis/.julia/v0.4/MXNet/test/runtests.jl:9

 in include at ./boot.jl:261

 in include_from_node1 at ./loading.jl:333

 in process_options at ./client.jl:280

 in _start at ./client.jl:378

while loading /home/travis/.julia/v0.4/MXNet/test/unittest/symbolic-node.jl, in expression starting on line 139

while loading /home/travis/.julia/v0.4/MXNet/test/runtests.jl, in expression starting on line 15
```
2. Julia 0.5 fails during visualization step, in function `to_graphviz`. I'll send PR to fix it, but for some reason optimizers, except of SGD are not working anymore.

3. Julia nightly build just not working, because of breaking changes in julia, I suppose.

**Comment by Arkoniak** [comment]
I found out why optimizers(except of sgd) no longer works. This is because optimizers use weight_decay and other small valued constants in definition. It turns out, that
```
w = copy(Array{Float32}([1, 2, 3]), mx.cpu())
println(copy(w))
> Float32[1.0,2.0,3.0]
println(copy(w * 0.0001))
> Float32[0.0001,0.0002,0.0003]
println(copy(w * 0.00001))
> Float32[1.0,2.0,3.0]
```
I can change all tolerance constants to 1e-4, also, some adjustment should be made as in https://github.com/dmlc/mxnet/issues/4493.
But I do not know, is it intended behavior? All was working fine in 0.8.

**Comment by pluskid** [comment]
@Arkoniak Thanks a lot! I will try to take a look this week and see if I can fix all those.

**Comment by Arkoniak** [comment]
I have found the reason of this strange behavior of NDArray multiplication. It's a subtle bug, and it happens due to the fact, that in julia
```
string(Float32(1e-4)) == "0.0001"
string(Float32(1e-5)) == "1.0f-5"
```
take notice of "f" in string representation. So, when float32 valued number goes to MXImperativeInvoke it is casted to string with "f" instead of "e"(https://github.com/dmlc/MXNet.jl/blob/nnvm/src/ndarray.jl#L1002) and libmxnet unable to parse it back to float. I can see two solutions:
1. perform cast to string via `@sprintf("%g", ...)` in all functions, that uses real in mxnet api calls: `mul_to!`, `div_from!` etc, or
2. add type check in `_get_ndarray_function_def` and cast Real with `@sprintf`, not `string`.

It's a small fix, I can send PR if needed of any of two options.

**Comment by pluskid** [comment]
@Arkoniak Great! Thanks! Please submit a PR for this. I believe there is a function called `dump_mx_param` that is responsible for converting all values passed to libmxnet. If you could add a suitable specialization for floating point, then I guess this should be fixed.

**Comment by Arkoniak** [comment]
1. Unfortunately `dump_mx_param` was not a good choice, because it changes order of elements in tuple, and that breaks `test_kwargs()` in `unittest/ndarray.jl`
2.  Unfortunately, travis still break: https://travis-ci.org/Arkoniak/MXNet.jl/builds/189848816 but it looks like this is travis problem. Since error message about missed `Profiler` function, may be it is this commit that is responsible:  https://github.com/dmlc/mxnet/pull/4544, because this error appeared only today.

**Pull request merged**
