### PR TITLE
Added initializers for Spatial Transformer Networks (STN) layers

### PR DESCRIPTION
**Pull request by facundoq**
Spatial Transformer Networks were added to MXNet back in July 2016 (https://github.com/dmlc/mxnet/pull/2547/commits/12cc483c1c235b14ef12ab7cd12574d4b12d1f6c). To use them, specialized initializers are needed for the weights in the location network and the bilinear filter.  I've followed the implementation for the python frontend. Not sure if these needs testing from the Julia side since the core c++ functionality is already being tested by through python api in the MXNet repo.

### CODE REVIEW

**Comment by vchuravy** [comment]
Tests are always greatly appreciated. Especially to make sure that potentially slight differences between the Python and Julia frontend are caught early.

**Comment by pluskid** [comment]
+1 for testing. However, it seems we do not have infrastructures to test initializers. I'm merging this PR for now.

**Comment by facundoq** [comment]
Great! I can submit another PR that adds an example that trains a lenet
with an stn layer on MNIST, as in the Python front-end.

Maybe that's sufficient "testing" for now and also helps in providing
documentation for the API.

Would you be up for mergjng that too?

Merged #223 <https://github.com/dmlc/MXNet.jl/pull/223>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dmlc/MXNet.jl/pull/223#event-1023184264>, or mute the
thread

**Comment by pluskid** [comment]
That would be great! I think It could serve as an example rather than a test.

**Comment by vchuravy** [comment]
The `init_bilinear` fails with:

```
INFO: Initializing parameters...
ERROR: LoadError: MethodError: no method matching zeros(::MXNet.mx.NDArray)
you may have intended to import Base.zeros
Closest candidates are:
  zeros{N,T<:Union{Float16,Float32,Float64,Int32,UInt8}}(!Matched::Type{T<:Union{Float16,Float32,Float64,Int32,UInt8}}, !Matched::Tuple{Vararg{Int64,N}}) at /home/wallnuss/.julia/v0.5/MXNet/src/ndarray.jl:177
  zeros{N,T<:Union{Float16,Float32,Float64,Int32,UInt8}}(!Matched::Type{T<:Union{Float16,Float32,Float64,Int32,UInt8}}, !Matched::Tuple{Vararg{Int64,N}}, !Matched::MXNet.mx.Context) at /home/wallnuss/.julia/v0.5/MXNet/src/ndarray.jl:180
  zeros{T<:Union{Float16,Float32,Float64,Int32,UInt8}}(!Matched::Type{T<:Union{Float16,Float32,Float64,Int32,UInt8}}, !Matched::Int64...) at /home/wallnuss/.julia/v0.5/MXNet/src/ndarray.jl:185
  ...
 in _init_bilinear(::MXNet.mx.XavierInitializer, ::Symbol, ::MXNet.mx.NDArray) at /home/wallnuss/.julia/v0.5/MXNet/src/initializer.jl:62
 in init(::MXNet.mx.XavierInitializer, ::Symbol, ::MXNet.mx.NDArray) at /home/wallnuss/.julia/v0.5/MXNet/src/initializer.jl:23
```

**Comment by facundoq** [comment]
@vchuravy Yeah, I thought that since STNs use bilinear filtering to perform the affine transform that layer was also used in the implementation but apparently it's not. So I actually never tested that part (but thought I was doing so). 

It also has a few bugs: a mixup with the row-major vs column-major stuff in `init_bilinear` and `_init_loc_bias`, and `array=...` vs `array[:]=..." . I've a fix for both, and I've actually checked now that `_init_bilinear` works as in the python version.  

However, I've been working on this for a few days now and I can't get a lenet+stn network to train with mnist, although the localisation network is the same as in the python version, and i'm initializing the loc_bias with `array[:]=[1.0, 0, 0, 1.0, 0, 0]`. I'll resubmit the PR as soon as I figure it out.

**Pull request merged**
