### PR TITLE
added ADAM SGD

### PR DESCRIPTION
**Pull request by cbecker**
This adds the ADAM SGD algorithm.

I am decaying the rate manually in the ADAM functions, as I was not sure how to integrate it properly with the other MXNet learning rate functions.

### CODE REVIEW

**Comment by cbecker** [comment]
also, I am not sure if the parameters (beta1Power, beta2Power, etc) should be Float64 or Float32.

**Comment by pluskid** [comment]
@cbecker Thanks! The learning rate and decay looks fine. I will do some refactoring later on to make use of existing learning rate scheduler (the current interface is not complete yet, so decay is not supported).

Before I merge this, could you explain the choice of `Float32` for `beta1Power`, `beta2Power`? Thanks again!

**Comment by cbecker** [comment]
Actually they should be Float64, I am not sure why I wrote Float32. I will fix it now.

Which machine precision is used inside MXNet? I suppose weights are converted to float, to speed up computations (and on GPUs because most GPUs do not work well with doubles)

**Comment by pluskid** [comment]
@cbecker Internally, Float32 is used for tensors and arrays. But for scalar parameters, anything should be fine though. I was just wanting to make sure that I did not miss some special requirement that is needed for the ADAM solver.

**Comment by cbecker** [comment]
Ok I see, no problem, then it should be fine now. You can merge.
As side note, in my experiments ADAM converges much faster than SGD, even with the default params.

**Comment by pluskid** [comment]
Thanks! Oh, Great! I will try adam later!

**Pull request merged**
