### PR TITLE
Added MXNET_COMMIT env variable for upstream commit/tag

### PR DESCRIPTION
**Pull request by joshbode**
Setting the `MXNET_COMMIT` environment variable to a tag, branch or hash
will use that version of the upstream mxnet repo in building the libmxnet
shared object.

Additionally, the upstream submodules are cleared (and reinitialised)
every build to prevent some issues when submodules make changes
(squashes, etc).

### CODE REVIEW

**Comment by pluskid** [comment]
@joshbode Thanks a lot! Can you add a few sentences to the installation doc ( http://dmlc.ml/MXNet.jl/latest/user-guide/install/#Manual-Compilation-1 ) about this?

**Comment by joshbode** [comment]
Good idea :) Done

**Comment by pluskid** [comment]
Fantastic!

**Comment by joshbode** [comment]
Thanks!

**Pull request merged**
