### PR TITLE
basic interface for setting and getting attributes

### PR DESCRIPTION
**Pull request by vchuravy**
In response to https://github.com/dmlc/mxnet/pull/685/

I suppose we would want as API:

````julia
mx.Data(name=:data, attributes = Dict(:key, "value"))
````

### CODE REVIEW

**Comment by pluskid** [comment]
Thanks! Yes, that kind of interface is better, and we should encourage the user to set the attributes at the beginning instead of modifying it dynamically.

**Comment by pluskid** [comment]
About the interface for specifying the attributes upon creating the symbol (if you are working on that):

* I prefer `attrs` over `attributes`, just to be consistent with `get_attr`, `set_attr`
* We should probably enforce that all the values must be `AbstractString`s.

**Comment by vchuravy** [comment]
Also the key values? These are currently set to be symbols, but that is
just personal preference.

**Comment by pluskid** [comment]
Symbols for key is fine imo and is kind of Julia-ish

**Comment by tbreloff** [comment]
My 2 cents... keys/values should be symbols if you can swing it. There's too much baggage that comes with using strings (ascii vs utf, etc) that is best avoided if possible.

**Comment by pluskid** [comment]
@tbreloff I agree with you. But for values, because they are suppose to represent arbitrary values (e.g. numbers, tuples, etc.), I don't think it make sense to use symbols. The values should actually be of type `Any`, but this will make the backend implementation super complicated, so we just go with string currently. The corresponding party who uses specific attributes is responsible to decode the actual value from the string.

**Comment by tbreloff** [comment]
So then Dict{Symbol,Any} is probably best. I think it adds too much complexity to require all inputs to be strings, especially if "they are suppose to represent arbitrary values (e.g. numbers, tuples, etc.)"

**Comment by vchuravy** [comment]
@tbreloff I agree with you that for the user working with Any is the nicest, but the backend can only handle strings. In theory we could serialize and deserialize attributes.

**Comment by pluskid** [comment]
I would like to keep the interface here rather light-weighted. String should be OK for commonly used values (symbols, strings, and probably integers, etc.), and this is how the underlying parameters for all operators are passed back into the libmxnet backend.

Attaching complicated objects is possible only if the user explicitly serialize it. I would like to make the interface in this case as difficult to use as possible as this should only be considered a temp workaround for something that should probably be implemented in another way. The reason is that complicated / opaque attributes attached to a symbolic node, when dumped to JSON string, will be impossible to decode from another frontend (e.g. Python or R).

**Comment by vchuravy** [comment]
While thinking about how I would use this for setting lr for layers I realized that the return value of `get_attr` should probably be a `Nullable{String}` and not throw a error, since otherwise there is no way of checking whether or not an attribute is available.

**Comment by tqchen** [comment]
Just a reminder about ```set_attr``` function and its possible consequences is discussed here https://github.com/dmlc/mxnet/blob/master/include/mxnet/c_api.h#L475

**Comment by pluskid** [comment]
@tqchen Thanks! I added a warning to the doc of `set_attr`, but probably we should rename it to `_set_attr` to discourage it from being called explicitly. 

@vchuravy Yes I think that makes sense. Alternatively, we could use similar thing as the `get` interface (see [here](http://docs.julialang.org/en/release-0.4/stdlib/collections/?highlight=get#Base.get)) as in Julia base -- allow the user to supply a default value. I personally find Julia `Nullable` a bit verbose and inconvenient to manipulate, but I'm fine with either option.

**Pull request merged**
