### PR TITLE
Better mxnet home handling

### PR DESCRIPTION
**Pull request by nstiurca**
Sometimes, `libmxnet.so` is not necessarily in a `lib` subdirectory, such as when using the one installed by Python's `pip`. This patch will search both `$MXNET_HOME` and `$MXNET_HOME/lib` for the shared library.

### CODE REVIEW

**Comment by nstiurca** [comment]
So I branched off `0.3.0` tag. It looks like that contains some commits that are not in `master`. This PR is really just the last commit. Let me know if/how you want me to rebase.

**Comment by iblis17** [comment]
could you show where `pip` put your `libmxnet.so`?

**Comment by nstiurca** [comment]
```/usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so```
(similar for Python 2.7)

**Comment by iblis17** [comment]
Appveyor failure is network issue.

**Comment by iblis17** [comment]
committed via 883cdd39d

**Pull request closed without merging**
