### PR TITLE
New Optimizers

### PR DESCRIPTION
**Pull request by Arkoniak**
Implemented some new optimizers, as was requested in [https://github.com/dmlc/MXNet.jl/issues/11](https://github.com/dmlc/MXNet.jl/issues/11)

* AdaDelta
* AdaGrad
* AdaMax
* RMSProp
* Nadam

Also, made slight change in ADAM code, as written in [https://arxiv.org/pdf/1412.6980v8.pdf](https://arxiv.org/pdf/1412.6980v8.pdf): "Note that the efficiency of algorithm 1 can, at the expense of clarity, be improved upon by changing the order of computation, e.g.  by replacing the last three lines in the loop"

New optimizers can be tested in examples/mnist/mlp-test.jl

### CODE REVIEW

**Comment by pluskid** [comment]
Thanks a lot!

**Comment by vchuravy** [comment]
This is great! Thank you.

**Comment by vchuravy** [comment]
We should probably add correctness tests for these optimizers.

**Comment by pluskid** [comment]
Wouldn't `mnist_fit_and_predict` function as testing? Or do you mean unit test? I'm not sure what would be good way to unit test optimizers, apart from implementing then again in another way?

**Pull request merged**
