### PR TITLE
update appveyor script

### PR DESCRIPTION
**Pull request by vchuravy**
@pluskid can you enable appveyor on MXNet.jl?

Fixes: #191

### CODE REVIEW

**Comment by musm** [comment]
bump?

**Comment by pluskid** [comment]
@vchuravy Apparently I lost my memory. So we did have appveyor long time ago and disabled it at some point? I cannot find where to enable it now.

**Comment by vchuravy** [comment]
Well we had the scripts in place, but we might never have it activated before. To get started see https://www.appveyor.com/docs/

**Comment by pluskid** [comment]
Thanks! I have added the project from scratch and enabled the building. A badge is also added to the README. The first build seem to be failed while downloading the package.

**Comment by pluskid** [comment]
https://ci.appveyor.com/project/pluskid/mxnet-jl/build/job/dq8o4boa49lvqr99

**Pull request merged**
