### PR TITLE
Reexporting NDArray and SymbolicNode

### PR DESCRIPTION
**Pull request by iblis17**

### CODE REVIEW

**Comment by pluskid** [comment]
Thanks! LGTM, but why are we exporting `NDArray` and `SymbolicNode` as oppose to keeping everything under `mx`? Is there a particular scenario that you have in mind that this will make it easier?

**Comment by iblis17** [comment]
This is an initial work for reexporting.
Feel free to list others here you want to export. :)

**Comment by iblis17** [comment]
I added tons of exports.
Good to go?

**Comment by pluskid** [comment]
travis error-ed, otherwise LGTM.

**Comment by iblis17** [comment]
ok, i fixed the tests.

**Pull request merged**
