### PR TITLE
Positional arguments in symbolic API need type restriction.

### PR DESCRIPTION
**Pull request by vchuravy**
This fixes the issue noted in #132, but is orthogonal to #133

### CODE REVIEW

**Comment by pluskid** [comment]
@vchuravy Thanks! If I understand correctly, we should still merge #133 , right?

**Comment by vchuravy** [comment]
Yes, but we will need to decide what happens with the current list of manual imports. https://github.com/dmlc/MXNet.jl/blob/master/src/MXNet.jl#L17-L18
The reason why I put that auto-import in was to prevent issues like  #42

**Comment by pluskid** [comment]
@vchuravy My understanding is as long as we use proper type annotation for the mx functions, auto-import should be fine.

**Comment by vchuravy** [comment]
That is true, we probably should then also to auto-import for NDArray and remove the manual imports? 

We could even try to generate a list of the auto-imported functions and put that as a note in the manual.

**Comment by pluskid** [comment]
@vchuravy Sounds like a good idea!

**Pull request merged**
