### PR TITLE
cblas: import all func prototype into header

### PR DESCRIPTION
**Pull request by iblis17**
according to this PR in MXNet: https://github.com/apache/incubator-mxnet/pull/7741

### CODE REVIEW

**Comment by iblis17** [comment]
hmm, what's wrong with appveyor?
https://ci.appveyor.com/project/pluskid/mxnet-jl/build/1.0.64/job/5h4y9wo1173tacax#L63

**Comment by iblis17** [comment]
please checkout the current `cblas.h`:

```c
└─[iblis@kaladbolg]% clang -E cblas.h | tail                                                                           
       const blasint clda, const blasint cldb);                                                                        
                                                                                                                       
void cblas_sgeadd(const enum CBLAS_ORDER CORDER,const blasint crows, const blasint ccols, const float calpha, float *a,
 const blasint clda, const float cbeta,
    float *c, const blasint cldc);                                                                                     
void cblas_dgeadd(const enum CBLAS_ORDER CORDER,const blasint crows, const blasint ccols, const double calpha, double *
a, const blasint clda, const double cbeta,                 
    double *c, const blasint cldc);                                                                                    
void cblas_cgeadd(const enum CBLAS_ORDER CORDER,const blasint crows, const blasint ccols, const float *calpha, float *a
, const blasint clda, const float *cbeta,                  
    float *c, const blasint cldc);                                                                                     
void cblas_zgeadd(const enum CBLAS_ORDER CORDER,const blasint crows, const blasint ccols, const double *calpha, double
*a, const blasint clda, const double *cbeta,               
    double *c, const blasint cldc);
```
```c
┌─[~/git/MXNet/deps]                                       
| [Venv(py36)] [ cblas] [-- INSERT --]                    
└─[iblis@kaladbolg]% clang -DINTERFACE64 -E cblas.h | tail
       const blasint clda, const blasint cldb);            
                             
void cblas_sgeadd64_(const enum CBLAS_ORDER CORDER,const blasint crows, const blasint ccols, const float calpha, float
*a, const blasint clda, const float cbeta,
    float *c, const blasint cldc);
void cblas_dgeadd64_(const enum CBLAS_ORDER CORDER,const blasint crows, const blasint ccols, const double calpha, doubl
e *a, const blasint clda, const double cbeta,
    double *c, const blasint cldc);
void cblas_cgeadd64_(const enum CBLAS_ORDER CORDER,const blasint crows, const blasint ccols, const float *calpha, float
 *a, const blasint clda, const float *cbeta,
    float *c, const blasint cldc);
...
```

**Comment by iblis17** [comment]
ready for review, please squash it while merging

**Comment by vchuravy** [comment]
Manually merged as 873715b, thank you for your work!

**Pull request closed without merging**
